// Generates 3 variants of a 32x32 pixel-art rubber duck, then upscales each to
// 64/96/180 PNG outputs. Plus a 32x32 blink-frame (eyes-closed) for the
// production variant. Output:
//   _design/mascot/variant_1.png ... variant_3.png  (96px previews)
//   public/mascot.png                                (96px production)
//   public/mascot-blink.png                          (96px blink frame)
//   public/mascot-32.png                             (32px nav)
//   public/mascot-180.png                            (180px favicon source)
//
// Pixel grids are hand-coded with a 5-color palette:
//   . = transparent
//   y = duck-yellow body  (#f9c47a)
//   o = darker bill/feet  (#e89c4d)
//   k = outline / pupil   (#1c1d2a)
//   w = white eye / cheek (#f4ebd9)
//   s = steam highlight   (#ffd599) — body-shade
//
// Three variants explore different silhouette ideas; the most legible is
// promoted to public/mascot.png.

import { writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const OUT_DESIGN = join(__dirname, "..", "_design", "mascot");
const OUT_PUBLIC = join(__dirname, "..", "public");

const PALETTE = {
  ".": [0, 0, 0, 0],
  y: [0xf9, 0xc4, 0x7a, 255],
  s: [0xff, 0xd5, 0x99, 255],
  o: [0xe8, 0x9c, 0x4d, 255],
  k: [0x1c, 0x1d, 0x2a, 255],
  w: [0xf4, 0xeb, 0xd9, 255],
  b: [0xb8, 0xd8, 0xe6, 255], // eye highlight steam-blue
};

// Variant 1: side-profile sitting duck, head turned slightly forward.
// 32x32 pixel grid. Eyes open.
const V1_OPEN = `
................................
................................
................................
..........kkkkk.................
.........kyyyyyk................
........kysyyyyyk...............
.......kyysyyyyyyk..............
.......kysyywksyyyk.............
.......kyywwbkyssyk.............
.......kyywksysyyykk............
.......kyysyyyyysyyk............
.......kyysyyyyyyyykk...........
.......kyysyyyyyyyssyk..........
.......kysyyyyyyyyyyyk..........
.......kysyyyyyyyysyyk..........
......kyysyyyyyyyysyyyk.........
......kyysyyyyyyysyyyyk.........
......kysyyyyyyyysyyyyyk........
.....kyysyyyyyyyyyyyyyyk........
.....kyysyyyyyyyyysyyyyk........
....kyysyyyyyyyysyyyyyyk........
....kyssyyyyyyyysyyyyyyk........
....kyssyyyyyyyyyyyyyyyk........
....kysyyyyyyyyyysyyyyyk........
....kkyyyyyyyyyyysyyyyyk........
.....kkkkkyyyyyyyyyyyyyk........
......kkkkkkyyyyyyyyyyykkk......
.kookoookoyyyyyyyyyyyyyyk.......
.kookoooko..ooyyyyyyyyyyk.......
.kookoooko..oo..ookkkkkkk.......
.kookoooko..oo..ok..............
..........................yk...
`;

// Variant 1 blink frame: eyes closed (k pixels where eye whites were).
const V1_BLINK = V1_OPEN
  .split("\n")
  .map((row, ri) => {
    if (ri === 8 || ri === 9) {
      // close eye: replace ww/wk/kw/wb with kk
      return row.replace(/wb/g, "kk").replace(/wk/g, "kk").replace(/kw/g, "kk").replace(/ww/g, "kk");
    }
    return row;
  })
  .join("\n");

// Variant 2: front-facing chubby duck, both feet visible. Cute / round.
const V2_OPEN = `
................................
................................
................................
............kkkkkk..............
...........kyyyyyyk.............
..........kyssyyyyyk............
.........kyyssyyyyyyk...........
........kyyyssyyyyyyyk..........
........kyyyssyyyyyyyk..........
........kywkbkywkbkyyk..........
........kywwbkywwbkyyk..........
........kywkbkywkbkyyk..........
........kyyyyyyyyyyyyk..........
........kyyyyooooyyyyk..........
........kyyyooooooyyyk..........
........kyyyyyyyyyyyyk..........
.......kyyyssyyyyyyyyyk.........
......kyyyssyyyyyyyssyyk........
.....kyyyssyyyyyyyyssyyyk.......
....kyyyyyyyyyyyyyyyyyyyyk......
....kyyyyyyyyyyyyyyyyyyyyk......
....kyyyyyyyyyyyyyyyyyyyyk......
....kyyyyyyyyyyyyyyyyyyyyk......
....kyyyyyyyyyyyyyyyyyyyyk......
.....kyyyyyyyyyyyyyyyyyyk.......
.....kyyyyyyyyyyyyyyyyyyk.......
......kkyyyyyyyyyyyyyyykk.......
.......kkkkooookoookkkkk........
..........koooo.koooo...........
..........koooo.koooo...........
..........kkkkk.kkkkk...........
................................
`;

const V2_BLINK = V2_OPEN
  .split("\n")
  .map((row, ri) => {
    if (ri === 9 || ri === 10 || ri === 11) {
      return row.replace(/wb/g, "kk").replace(/wk/g, "kk").replace(/kw/g, "kk").replace(/ww/g, "kk");
    }
    return row;
  })
  .join("\n");

// Variant 3: 3/4 view duck with bath-bubble accent (showcase the bath-house theme)
const V3_OPEN = `
................................
......b.....b...................
....b....b...b.....b............
...b...b....b....b..............
......b....b....b....b..........
............kkkkk...............
...........kyyyyyk..............
..........kysyyyyyk.............
..........kyysyyyyyk............
.........kyyywkyyyyyk...........
.........kyywwkyysyyk...........
.........kyywkyyysyyk...........
.........kyysyyyyysyk...........
........kyyysyyyyyyyyk..........
........kyyysyyyyyyysyk.........
.......kyyssyyyyyyyssyyk........
......kyyssyyyyyyyssyyyyk.......
.....kyyssyyyyyyyssyyyyyyk......
....kyyssyyyyyyyssyyyyyyyyk.....
....kyyyyyyyyyyyssyyyyyyyyk.....
....kyyyyyyyyyyssyyyyyyyyyk.....
....kyyyyyyyyyyyyyyyyyyyyyk.....
.....kyyyyyyyyyyyyyyyyyyyyk.....
......kyyyyyyyyyyyyyyyyyyk......
.......kkyyyyyyyyyyyyyykk.......
.........kkkooookoooookk........
.........koooo.koooo............
.........koooo.koooo............
.........koooo.koooo............
..........kkk...kkk.............
................................
................................
`;

const V3_BLINK = V3_OPEN
  .split("\n")
  .map((row, ri) => {
    if (ri === 9 || ri === 10 || ri === 11) {
      return row.replace(/wk/g, "kk").replace(/ww/g, "kk").replace(/kw/g, "kk").replace(/wb/g, "kk");
    }
    return row;
  })
  .join("\n");

function gridToBuffer(grid) {
  const rows = grid.trim().split("\n").map((r) => r.padEnd(32, "."));
  const W = 32, H = 32;
  const buf = Buffer.alloc(W * H * 4);
  for (let y = 0; y < H; y++) {
    const row = rows[y] || ".".repeat(W);
    for (let x = 0; x < W; x++) {
      const ch = row[x] || ".";
      const px = PALETTE[ch] || PALETTE["."];
      const i = (y * W + x) * 4;
      buf[i] = px[0]; buf[i + 1] = px[1]; buf[i + 2] = px[2]; buf[i + 3] = px[3];
    }
  }
  return buf;
}

async function renderToPng(grid, size, outPath) {
  const raw = gridToBuffer(grid);
  await sharp(raw, { raw: { width: 32, height: 32, channels: 4 } })
    .resize(size, size, { kernel: "nearest" })
    .png({ compressionLevel: 9 })
    .toFile(outPath);
}

async function ensureDir(d) {
  if (!existsSync(d)) await mkdir(d, { recursive: true });
}

async function main() {
  await ensureDir(OUT_DESIGN);
  await ensureDir(OUT_PUBLIC);

  // 96px previews of each variant
  await renderToPng(V1_OPEN, 96, join(OUT_DESIGN, "variant_1.png"));
  await renderToPng(V2_OPEN, 96, join(OUT_DESIGN, "variant_2.png"));
  await renderToPng(V3_OPEN, 96, join(OUT_DESIGN, "variant_3.png"));
  console.log("[mascot] 3 variant previews written to _design/mascot/");

  // SHIP variant 2 as production (front-facing is most-recognizable as a duck)
  // Provide multiple sizes for nav (32), production (96), and favicon source (180)
  await renderToPng(V2_OPEN, 96, join(OUT_PUBLIC, "mascot.png"));
  await renderToPng(V2_BLINK, 96, join(OUT_PUBLIC, "mascot-blink.png"));
  await renderToPng(V2_OPEN, 32, join(OUT_PUBLIC, "mascot-32.png"));
  await renderToPng(V2_OPEN, 180, join(OUT_PUBLIC, "mascot-180.png"));
  console.log("[mascot] production v2 → public/mascot{,-blink,-32,-180}.png");
}

main().catch((e) => { console.error(e); process.exit(1); });
